image:
    name: hashicorp/terraform:light

before_script:
    - rm -rf .terraform
    - terraform -version

stages:
    - validate

validate:
    stage:
        - validate
    tags: 
        - terraform-aws
    script:
        - echo "i work"
    only:
        - branches