image:
    name: hashicorp/terraform:light

before_script:
    - rm -rf .terraform
    - terraform --version

stages:
    - validate

validate:
    stage: validate
    script:
        - echo "i work"
    tags: garry-runner
    only:
        - branches