image:
    name: hashicorp/terraform:light
    entrypoint:
        - '/usr/bin/env'
        - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
    PLAN: $CI_PROJECT_DIR/plan.tfplan

before_script:
    - apk add curl
    - rm -rf .terraform
    - terraform --version
    - mkdir -p ~/.aws
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - cd ./infra
    - terraform init

stages:
    - validate
    - plan
    - apply

validate:
    stage: validate
    tags:
    - terraform-aws
    script:
      - terraform validate
      - terraform fmt -check=true
    only:
      - branches

merge review:
   stage: plan
   tags:
   - terraform-aws
   script:
     - terraform plan -out=$PLAN
     - echo \`\`\`diff > plan.txt
     - terraform show -no-color ${PLAN} | tee -a plan.txt
     - echo \`\`\` >> plan.txt
     - sed -i -e 's/  +/+/g' plan.txt
     - sed -i -e 's/  ~/~/g' plan.txt
     - sed -i -e 's/  -/-/g' plan.txt
     - MESSAGE=$(cat plan.txt)
     - >-
       curl -X POST -g -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}" 
       --data-urlencode "body=${MESSAGE}" 
       "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}/discussions"
   artifacts:
     name: plan
     paths:
       - $PLAN
   only:
     - merge_requests

plan production:
  stage: plan
  tags:
  - terraform-aws
  script:
    - terraform plan -out=$PLAN
  artifacts:
    name: plan
    paths:
      - $PLAN
  only:
    - master
      
apply:
  stage: apply
  script:
    - terraform apply -input=false $PLAN
    - DYNAMIC_ENVIRONMENT_URL=$(terraform output -no-color env-dynamic-url)
    - echo "DYNAMIC_ENVIRONMENT_URL=$DYNAMIC_ENVIRONMENT_URL" >> deploy.env
  dependencies:
    - plan production
  only:
    - master
  when: manual
  