variables:
  PLAN: $CI_PROJECT_DIR/plan.tfplan
  APP_VERSION_FILE: $CI_PROJECT_DIR/app_version.txt
  DOCKER_IMAGE_NAME: $AWS_REGISTRY_URL/$CI_PROJECT_NAME

stages:
  - validate
  - build
  - plan
  - apply

include:
  - local: .gitlab/ci/terraform.gitlab-ci.yml
  - local: .gitlab/ci/docker.gitlab-ci.yml
  - local: .gitlab/ci/triggers.gitlab-ci.yml
