.docker_pre:
  stage: build
  before_script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - aws ecr get-login-password --region eu-west-2 | docker login -u AWS --password-stdin $AWS_REGISTRY_URL
    - export APP_VERSION=$(cat $APP_VERSION_FILE)
  tags:
    - shell

feature build:
  script:
    - docker build -t $DOCKER_IMAGE_NAME:${APP_VERSION}-${CI_COMMIT_SHA::8} .
    - docker push $DOCKER_IMAGE_NAME:${APP_VERSION}-${CI_COMMIT_SHA::8}
  only:
    - branches
    - merge_requests
  except:
    - master

production build:
  script:
    - docker build -t $DOCKER_IMAGE_NAME:${APP_VERSION}-${CI_COMMIT_SHA::8} .
    - docker tag  $DOCKER_IMAGE_NAME:${APP_VERSION}-${CI_COMMIT_SHA::8} ${DOCKER_IMAGE_NAME}:${APP_VERSION}
    - docker push $DOCKER_IMAGE_NAME:${APP_VERSION}
    - docker push $DOCKER_IMAGE_NAME:${APP_VERSION}-${CI_COMMIT_SHA::8}
  only:
    - master
